SELECT TOP 20 * FROM customer;

-- Q1: What is the total revenue generated by male vs. female customers?

Select gender, SUM(purchase_amount) as revenue 
from customer 
group by gender

-- Q2: Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount, discount_applied
FROM customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3: Which are the top 5 products with the highest average review rating?

SELECT TOP 5 item_purchased, 
       ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY [Average Product Rating] DESC;

-- Q4: Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type, 
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5: Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status, 
    AVG(purchase_amount) AS avg_spend, 
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6: Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 
    item_purchased,
    (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

-- Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM customer
GROUP BY 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END
ORDER BY segment_count DESC;

-- Q8: What are the top 3 most purchased products within each category?

WITH ProductRanking AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_number
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category, item_purchased, purchase_count
FROM ProductRanking
WHERE rank_number <= 3
ORDER BY category, rank_number;

-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, 
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10: What is the revenue contribution of each age group?

SELECT 
    age_group, 
    SUM(purchase_amount) AS total_revenue,
    ROUND(SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) OVER(), 2) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;